### ISSUE TITLE
Suali diqqetle oxuyun ve alinan cavabada baxin.Sherti deyisherek Indexi tək yerdə duran elementləri remove ederek ekrana cap edin

### ISSUE THREAD

**Issue by Ferid-Memmedli** [NaghiAliyev/PragmatechFoundationProject#1]
https://github.com/NaghiAliyev/PragmatechFoundationProject/blob/4e1603e4e92627f126ae9f553886ca87fbbddbbf/Tasks/PythonTasks/Task-Week08-day05/CodeTasks/task_6.py#L5

**Comment by NaghiAliyev** [comment]
Səhvimi başa düşmüşəm, elementləri sildikcə yerləri dəyişdiyinə görə çıxan
cavab səhv olub axşam düzəldilmiş cavablar yüklənəcək. Səhv məndə imiş şərti nəzərə almayıbmışam.
